### ISSUE TITLE
The lsb_release command is not available on some Debian VPS installs

### ISSUE THREAD

**Issue by russkel** [fabtools/fabtools#123]
Using fabtools.system.distrib_codename() doesn't seem to work on Debian wheezy, at least a stock install.

> Fatal error: run() received nonzero return code 127 while executing!
> 
> Requested: lsb_release --codename --short
> Executed: /bin/bash -l -c "lsb_release --codename --short"
> 
> =============================== Standard output ===============================
> # /bin/bash: lsb_release: command not found
> 
> Aborting.

**Comment by ronnix** [comment]
Looks like VPS providers often customize their images. I've been surprised more than once by these customizations. (For example, it looks like OVH ships Ubuntu 14.04 VPS's with APT's crontab entry disabled, preventing automatic security updates to work...)
