### ISSUE TITLE
Unnecessary installation of python-dev for setuptools

### ISSUE THREAD

**Issue by deronnax** [fabtools/fabtools#251]
in fabtools/require/python.py#L50, python-dev is installed if setup_tools is not present on the computer.
1. On Ubuntu, python-dev come with a lot of dependencies, including a full gcc, which is a clumsy and dangerous thing to have on a production server (http://security.stackexchange.com/questions/12113/installing-development-tools-on-production-server-security-risk)
1. I managed to install setuptools on a vanilla ubuntu using the simple install method promoted by setuptools (https://pypi.python.org/pypi/setuptools#unix-wget), which makes me think that the python-dev package is not necessary.

I will propose a pull request in some day if you don't fix it before I do.

**Comment by deronnax** [comment]
Up. What can we do about it :) ? I have many projects with  full python-only dependencies (even for LDAP and MySQL), and this is veeeery annoying to me (and I'm sure a bunch of other people)

**Comment by ronnix** [comment]
We could add an extra `install_build_deps=True` keyword argument to `require.python.setuptools()` (and its callers) so that you could switch this off when you don't want to install the build tools and development headers on the target system. What do you think?

**Comment by deronnax** [comment]
I think that install_build_deps default value should be "False", [1] but I'm OK :)
(yeah, it would break compat but that behavior of installing developpment tools by default is really hardmful)
