### ISSUE TITLE
requires.files.file(url) fails with urls containing character '&'

### ISSUE THREAD

**Issue by davidcaste** [fabtools/fabtools#261]
Hi!

Function `requires.files.file(url)` fails when the url contains the character `&`, as found e.g. in Amazon S3 download links, and many more places.

Taking a look to the source code, `wget` is invoked the following way:

```
func('wget --progress=dot:mega %(url)s -O %(path)s' % locals())
```

The problem could be easily solved using double quotes around `%(url)s` and `%(path)s` in the following way:

```
func('wget --progress=dot:mega "%(url)s" -O "%(path)s"' % locals())
```

Thanks!

**Comment by hobbestigrou** [comment]
It's merged.
