### ISSUE TITLE
fabtools.postgres.user_exists() quick fix

### ISSUE THREAD

**Issue by ghost** [fabtools/fabtools#4]
For some reasons (gremlins ?) the test `(res == "1")` does not work even if the psql command returns `"1"`
I found it worked better using `("1" in res)`, without any `str.strip()`, etc...

**Comment by tony** [comment]
> You should probably avoid directly connecting as root on your server, and I would even recommend disabling it altogether by adding PermitRootLogin no to /etc/ssh/sshd_config.

That's true

But it's not a solution. root/sudo shouldn't be encumbered by permission issues

Ended up doing https://github.com/fabtools/fabtools/issues/4#issuecomment-8845152. That is hacky, but in the end, I'm using fabtools for convenience and just getting stuff deployed. I'm not a full-time devops person :smile:

**Comment by funerr** [comment]
Any elegant solution yet?
